# NYC Taxi Trips Exploration

In [ ]:
# Import libraries to read
import pandas as pd

# try to read a single file (green taxis):
trips = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-01.parquet')
trips.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2022-01-01 00:14:21,2022-01-01 00:15:33,N,1.0,42,42,1.0,0.44,3.5,0.50,0.5,0.00,0.0,None,0.3,4.80,2.0,1.0,0.00
1,1,2022-01-01 00:20:55,2022-01-01 00:29:38,N,1.0,116,41,1.0,2.10,9.5,0.50,0.5,0.00,0.0,None,0.3,10.80,2.0,1.0,0.00
2,1,2022-01-01 00:57:02,2022-01-01 01:13:14,N,1.0,41,140,1.0,3.70,14.5,3.25,0.5,4.60,0.0,None,0.3,23.15,1.0,1.0,2.75
3,2,2022-01-01 00:07:42,2022-01-01 00:15:57,N,1.0,181,181,1.0,1.69,8.0,0.50,0.5,0.00,0.0,None,0.3,9.30,2.0,1.0,0.00
4,2,2022-01-01 00:07:50,2022-01-01 00:28:52,N,1.0,33,170,1.0,6.26,22.0,0.50,0.5,5.21,0.0,None,0.3,31.26,1.0,1.0,2.75

In [ ]:
# Diference with green from other year?
trips2 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-01.parquet')
trips2.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-01-01 00:03:01,2025-01-01 00:17:12,N,1.0,75,235,1.0,5.93,24.70,...,0.5,6.80,0.00,NaN,1.0,34.00,1.0,1.0,0.00,0.0
1,2,2025-01-01 00:19:59,2025-01-01 00:25:52,N,1.0,166,75,1.0,1.32,8.60,...,0.5,0.00,0.00,NaN,1.0,11.10,2.0,1.0,0.00,0.0
2,2,2025-01-01 00:05:29,2025-01-01 00:07:21,N,5.0,171,73,1.0,0.41,25.55,...,0.0,0.00,0.00,NaN,1.0,26.55,2.0,2.0,0.00,0.0
3,2,2025-01-01 00:52:24,2025-01-01 01:07:52,N,1.0,74,223,1.0,4.12,21.20,...,0.5,6.13,6.94,NaN,1.0,36.77,1.0,1.0,0.00,0.0
4,2,2025-01-01 00:25:05,2025-01-01 01:01:10,N,1.0,66,158,1.0,4.71,33.80,...,0.5,7.81,0.00,NaN,1.0,46.86,1.0,1.0,2.75,0.0

Warning: Total number of columns (21) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
print(f'2022 has: {trips.shape}')
print(f'2025 has: {trips2.shape}')

2022 has: (62495, 20)
2025 has: (48326, 21)

## Diferencias detectadas en 2 ejemplos:
- ehail_fee in 2022 was null vs 2025 was NaN
- 2022 has 20 cols, 2025 has 21 cols (+ cbd_congestion_fee)

In [ ]:
common_cols = list(set(trips.columns) & set(trips2.columns))
diff_cols_trips = list(set(trips.columns) - set(trips2.columns))
diff_cols_trips2 = list(set(trips2.columns) - set(trips.columns))

print(f"Columns unique to 'trips': {diff_cols_trips}")
print(f"Columns unique to 'trips2': {diff_cols_trips2}")
print(f"Common columns: {common_cols}")

Columns unique to 'trips': []
Columns unique to 'trips2': ['cbd_congestion_fee']
Common columns: ['tolls_amount', 'passenger_count', 'improvement_surcharge', 'tip_amount', 'lpep_dropoff_datetime', 'fare_amount', 'congestion_surcharge', 'RatecodeID', 'extra', 'total_amount', 'DOLocationID', 'PULocationID', 'payment_type', 'mta_tax', 'trip_type', 'store_and_fwd_flag', 'trip_distance', 'VendorID', 'ehail_fee', 'lpep_pickup_datetime']

## Now let's check for the yellow trip data

In [ ]:
# try to read a single file (yellow taxis):
ytrips = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-01.parquet')
ytrips.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2022-01-01 00:35:40,2022-01-01 00:53:29,2.0,3.80,1.0,N,142,236,1,14.5,3.0,0.5,3.65,0.0,0.3,21.95,2.5,0.0
1,1,2022-01-01 00:33:43,2022-01-01 00:42:07,1.0,2.10,1.0,N,236,42,1,8.0,0.5,0.5,4.00,0.0,0.3,13.30,0.0,0.0
2,2,2022-01-01 00:53:21,2022-01-01 01:02:19,1.0,0.97,1.0,N,166,166,1,7.5,0.5,0.5,1.76,0.0,0.3,10.56,0.0,0.0
3,2,2022-01-01 00:25:21,2022-01-01 00:35:23,1.0,1.09,1.0,N,114,68,2,8.0,0.5,0.5,0.00,0.0,0.3,11.80,2.5,0.0
4,2,2022-01-01 00:36:48,2022-01-01 01:14:20,1.0,4.30,1.0,N,68,163,1,23.5,0.5,0.5,3.00,0.0,0.3,30.30,2.5,0.0

In [ ]:
ytrips2 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-01.parquet')
ytrips2.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [ ]:
print(f'yellow 2022 has: {ytrips.shape}')
print(f'yellow 2025 has: {ytrips2.shape}')

yellow 2022 has: (2463931, 19)
yellow 2025 has: (3475226, 20)

In [ ]:
ycommon_cols = list(set(ytrips.columns) & set(ytrips2.columns))
ydiff_cols_trips = list(set(ytrips.columns) - set(ytrips2.columns))
ydiff_cols_trips2 = list(set(ytrips2.columns) - set(ytrips.columns))

print(f"Columns unique to 'trips': {ydiff_cols_trips}")
print(f"Columns unique to 'trips2': {ydiff_cols_trips2}")
print(f"Common columns: {ycommon_cols}")

Columns unique to 'trips': ['airport_fee']
Columns unique to 'trips2': ['Airport_fee', 'cbd_congestion_fee']
Common columns: ['tpep_dropoff_datetime', 'fare_amount', 'tolls_amount', 'RatecodeID', 'passenger_count', 'improvement_surcharge', 'store_and_fwd_flag', 'extra', 'total_amount', 'tip_amount', 'congestion_surcharge', 'DOLocationID', 'PULocationID', 'trip_distance', 'VendorID', 'mta_tax', 'tpep_pickup_datetime', 'payment_type']

## Diferencias enccontradas en yellow
- airport_fee en 2022 vs Airport_fee en 2025 (+ cbd_congestion_fee)
- yellow tiene muchisimos mas viajes que green